# Proof of concept SConstruct for integrating C++ into FORTRAN

cxxsources=['testCxx.cc']
fsources=['test_Cxx_in_F.f']

envCxx=Environment(CXX='g++');
envCxx.Library('testCxx',cxxsources)

envF=Environment(FORTRAN='gfortran')
envF.Program('testF',fsources,LIBS=['testCxx','stdc++'],LIBPATH='.')
